### ISSUE TITLE
I just wanted to say, good job.

### ISSUE THREAD

**Issue by ferusinfo** [gergelyszabo94/csgo-trader-extension#224]
It i fairly admirable when someone makes an "auto-bump" script for my website and makes it open-source. Good job sir, the code looks clean ;)

Now i need to find a way to block your attempts :) Anyways, thanks for using the site 👍 

Source: I am csgotraders.net owner ;)

**Comment by gergelyszabo94** [comment]
@ferusinfo Hi there. I thought the site was completely abandoned at this point. Are you just starting to revive it?

**Comment by ferusinfo** [comment]
Frankly, if you are going to need anything that I can help out with (besides blocking auto-bumping :D) let me know, I will be more than happy to help and might even promote your extension on the site at some point ;)

Website was never abandoned. The thing is - I am the only person in this project handling everything, and while I have a stable full-time job and multiple side jobs, a website was out of focus of mine for a while (but I always kept it online and fixed minor issues when they were occuring)

But with COVID-19 situation and me having some more time at the moment, I must say my roadmap for the future updates for the website is quite large and clear ;)

**Comment by gergelyszabo94** [comment]
@ferusinfo that is great to hear, I tried contacting you about because my inventory was not loading when I tried adding trades, but received no response. I retry that every now and then and I just noticed that It did load this time! Is that a recent fix?

I would love if we could work out some kind of partnership. Frankly I was so disappointed by both Lounge and your site being seemingly abandoned that I had long term plans of making a site like that for trading of my own.

I just quit my job so I will have more time for these pet projects, and as I said some kind of partnership would be great, although it might be confusing for some people because of the similar names :)  Are you active on Steam? Do you want to keep contact there?

**Comment by ferusinfo** [comment]
Yea, the inventory fixes were introduced like 2-3 weeks ago by me as well as page load time optimization.

Since the project was launched in 2014 and actively developed until 2017 - when PUBG was released and CSGO trading went to shit, with 50% decrease of users on the website - since then I was mainly focused on maintaining the site in its form.

With 2020 giving me more time to work on this project and people coming back to csgo and trading, I  nowhave a lot of things to do, epecially that some of the code... was written poorly by me in 2014. 

I am now attending the site business almost everyday - like today I already implemented few backend fixes for idle database connections that were stopping the site under heavy loda.

I am almost always offline on Steam (since too many people are adding me), but you can reach me at my csgotraders email. If you will write who you are, I will definietely answer. Most of emails I am getting are quite... stupid ;)

Keep working on the extension! I will have an eye on it and if you will need any resources from me, let me know - I will think about it :)

**Comment by gergelyszabo94** [comment]
Alright, shooting an email now from gergely@gergely-szabo.com.

Let's continue there.
