### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by NixA01** [gergelyszabo94/csgo-trader-extension#470]
Solved

**Comment by gergelyszabo94** [comment]
This is quite a complex feature, there are plenty of things that can go wrong that I will list here.
I don't think that is the issue (since in the history it seems to match) but if you just want to accept "gift" (empty on your side with items on their side) offers then I would go with this:
![image](https://user-images.githubusercontent.com/3636827/203772674-19f4d17e-76f4-492d-b6b6-a2132fa79036.png)
It sounds like you already have these but:
- Make sure your Steam API key is set
- Tabs API access is enabled
- Your browser is open (all the time you want this to work)
- You are logged into Steam

One additional thing I recommend is having your Incoming Offers page open all the time.

**Comment by NixA01** [comment]
I tried everything above and even reinstalled the extension, sadly this issue still occurs. If you have any other suggestions that I can try it would be much of help.

**Comment by gergelyszabo94** [comment]
You could open the developer console on the trade offers page and wait for an accept event to occur and see if can see the extension attempting to accept the offer in the network tab or if you see any new errors.
