### ISSUE TITLE
Error when trying to instant sell items

### ISSUE THREAD

**Issue by coomierta** [gergelyszabo94/csgo-trader-extension#477]
I was trying to instant sell a bunch of crates I got and instant sell worked for the first few however now when I try it gives me an "error" with no other information.

Using chrome, thanks in advance.

![Caddaptuasdasdre](https://user-images.githubusercontent.com/121742699/210161733-20d20ae1-a806-47fc-a84b-299cc9d55157.PNG)

**Comment by coomierta** [comment]
This isn't an issue with just csgo items I get the same error when selling tf2 and steam items.

**Comment by gergelyszabo94** [comment]
Hello, I believe it's happening because Steam tightened their request limits. When you click on an item in your inventory the "Starting at" price displayed on your screenshot is loaded by Steam (even without the extension). When you click the extension's Instant Sell button it fetches the buy order price from Steam (so it knows at what price to list at to be sold right away). If you click around a lot in your inventory with or without the extension eventually Steam will limit you (you will notice this by the "Starting at" and "Volume" lines disappearing. One thing you can do about this is using the extension's Mass Listing feature by clicking the "Pointing hand" button, selecting the items you want to sell then checking the "Load prices for: Instant Sell" checkbox. 
![image](https://user-images.githubusercontent.com/3636827/210166611-089f92f5-ade1-48c2-8674-8c8d841ed1d0.png)
You will achieve the same result but the requests will be spread out more and you will be less likely to get limited because of them.
